// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum EntityType {
  CORE,
  CLAW,
  FOOD_SOURCE,
  PORTAL,
  RESOURCE_SPLIT,
  CONTROL_SPLIT,
  COUNTER,
  MODIFIER
}

enum ConnectionType {
  RESOURCE,
  CONTROL
}
