// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IModifierSystem {
  function mc_ModifierSystem_connect(bytes32 _modifierOrgan, bytes32 _targetOrgan) external;

  function mc_ModifierSystem_disconnect(bytes32 _modifierOrgan) external;
}
