// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IRSplitSystem {
  function mc_RSplitSystem_connect(bytes32 _resourceSplitOrgan, bytes32 _targetOrgan) external;

  function mc_RSplitSystem_disconnect(bytes32 _resourceSplitOrgan) external;
}
